In [1]:
import numpy as np

In [2]:
# wap to add list elements of array belonging to nth index and convert to new list 
l1 = [1,2,3,4,5]
l2 = [4,5,6,6,7]

In [9]:
l3 = []
for i in range(len(l1)):
    l3.append(l1[i]+l2[i])
print(l3)

[5, 7, 9, 10, 12]


In [136]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

In [137]:
a+b

array([3, 5, 7, 9])

In [138]:
a-b

array([-1, -1, -1, -1])

In [139]:
a/b

array([0.5       , 0.66666667, 0.75      , 0.8       ])

In [140]:
a*2

array([2, 4, 6, 8])

In [141]:
a**2

array([ 1,  4,  9, 16])

In [142]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [143]:
np.zeros(2)

array([0., 0.])

In [144]:
np.ones(4)

array([1., 1., 1., 1.])

In [145]:
np.full(5,10)

array([10, 10, 10, 10, 10])

In [146]:
np.arange(1,20,4)

array([ 1,  5,  9, 13, 17])

In [147]:
np.linspace(1,20,4)

array([ 1.        ,  7.33333333, 13.66666667, 20.        ])

In [148]:
np.arange(1,16,3)

array([ 1,  4,  7, 10, 13])

In [149]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [150]:
arr = np. array([2,3,4,5,6])

In [151]:
arr

array([2, 3, 4, 5, 6])

In [152]:
arr.shape

(5,)

In [153]:
arr = np. array([[2,3,4,5,6]])

In [154]:
arr

array([[2, 3, 4, 5, 6]])

In [155]:
arr.shape

(1, 5)

In [156]:
arr = np. array([[1,2,3,4,5],[2,3,4,5,6]])

In [157]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [158]:
#row and column
arr.shape 

(2, 5)

In [159]:
# number of dimensions
arr.ndim

2

In [160]:
# size of array
arr.size

10

In [161]:
# data type of array
arr.dtype

dtype('int64')

In [162]:
# memory size
arr.itemsize

8

In [163]:
arr1 = np.array([[True,True,False]])

In [164]:
arr1.dtype

dtype('bool')

In [165]:
arr1.itemsize

1

In [166]:
arr2 = np.array([[True,True,"a"]])

In [167]:
arr2.dtype

dtype('<U5')

In [168]:
arr2.itemsize

20

In [169]:
arr2.item

<function ndarray.item(*args)>

In [170]:
arr = np. array([[1,2,3,4,5],[2,3,4,5,6]])

In [171]:
# indexing and slicing
arr[1]

array([2, 3, 4, 5, 6])

In [172]:
arr[1,2]

np.int64(4)

In [173]:
#start:stop
arr[1:3] 

array([[2, 3, 4, 5, 6]])

In [174]:
arr = np. array([[1,2,3,4,5]])

In [177]:
arr[0]

array([1, 2, 3, 4, 5])

In [178]:
arr[:2]

array([[1, 2, 3, 4, 5]])

In [183]:
arr[0:]

array([[1, 2, 3, 4, 5]])

In [182]:
#entire row and fixed column
arr[:,1]

array([2])

In [187]:
#row, column
arr[:,0:2]

array([[1, 2]])

In [188]:
arr = np. array([[1,2],[3,4],[5,6]])

In [189]:
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [190]:
arr[0:2,:]

array([[1, 2],
       [3, 4]])

In [191]:
arr[1:2,:]

array([[3, 4]])

In [192]:
arr[1:3,:]

array([[3, 4],
       [5, 6]])

In [193]:
arr = np. array([[1,2,9],[3,4,2],[5,6,7]])

In [194]:
arr

array([[1, 2, 9],
       [3, 4, 2],
       [5, 6, 7]])

In [196]:
arr[1:3,1:3]

array([[4, 2],
       [6, 7]])

In [207]:
# mathematical operations
arr1 = np. array([[1,2,9],[3,4,2]])
arr2 = np. array([[3,1,2],[5,6,4]])

In [208]:
arr1+arr2

array([[ 4,  3, 11],
       [ 8, 10,  6]])

In [209]:
arr1-arr2

array([[-2,  1,  7],
       [-2, -2, -2]])

In [210]:
arr1*arr2

array([[ 3,  2, 18],
       [15, 24,  8]])

In [211]:
arr1/arr2

array([[0.33333333, 2.        , 4.5       ],
       [0.6       , 0.66666667, 0.5       ]])

In [212]:
arr1 **2

array([[ 1,  4, 81],
       [ 9, 16,  4]])

In [213]:
# reshaping
arr = np.array([[1,2,3,4]])

In [214]:
arr

array([[1, 2, 3, 4]])

In [215]:
arr.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [217]:
arr = np.array([[1,2,3,4,2,6,7]])

In [220]:
arr

array([[1, 2, 3, 4, 2, 6, 7]])

In [221]:
arr.reshape(7,1)

array([[1],
       [2],
       [3],
       [4],
       [2],
       [6],
       [7]])