In [1]:
import numpy as np

In [10]:
a = np.array([[2,3,4],[5,6,7]])

In [11]:
a

array([[2, 3, 4],
       [5, 6, 7]])

In [12]:
a.flatten()

array([2, 3, 4, 5, 6, 7])

In [13]:
a.T

array([[2, 5],
       [3, 6],
       [4, 7]])

In [14]:
a

array([[2, 3, 4],
       [5, 6, 7]])

In [15]:
a.sum()

np.int64(27)

In [16]:
a.mean()

np.float64(4.5)

In [34]:
a.max(axis=0)

array([5, 6, 7])

In [18]:
a.min()

np.int64(2)

In [19]:
a.std()

np.float64(1.707825127659933)

In [22]:
a.sum(axis=0)

array([ 7,  9, 11])

In [23]:
a.sum(axis=1)

array([ 9, 18])

In [24]:
a

array([[2, 3, 4],
       [5, 6, 7]])

In [27]:
b = np.array([1,3,2,6,4])

In [28]:
b

array([1, 3, 2, 6, 4])

In [42]:
np.sort(b)

array([1, 2, 3, 4, 6])

In [53]:
b

array([1, 2, 3, 4, 6])

In [54]:
a = np.array([[20,3,2],[5,60,7]])
a

array([[20,  3,  2],
       [ 5, 60,  7]])

In [55]:
a.sort(axis=0)

In [56]:
a

array([[ 5,  3,  2],
       [20, 60,  7]])

In [57]:
a.sort(axis=1)

In [58]:
a

array([[ 2,  3,  5],
       [ 7, 20, 60]])

In [60]:
a

array([[ 2,  3,  5],
       [ 7, 20, 60]])

In [61]:
c = np.array([[20,3,2,34],[5,60,7,21]])
c

array([[20,  3,  2, 34],
       [ 5, 60,  7, 21]])

In [64]:
c<10

array([[False,  True,  True, False],
       [ True, False,  True, False]])

In [76]:
c[c<10]

array([1, 4, 5])

In [77]:
c = np.array([1,31,4,5,90,64])

In [78]:
c

array([ 1, 31,  4,  5, 90, 64])

In [84]:
c[(c<10) | (c>60)]

array([ 1,  4,  5, 90, 64])

In [95]:
a = np.array([1,31,4,5,90,64])
b = np.array([11,10,3,2,11,4])
c = np.array([13,12,3,2,11,4])

In [96]:
np.concat([a,b])

array([ 1, 31,  4,  5, 90, 64, 11, 10,  3,  2, 11,  4])

In [97]:
np.concatenate([a,b])

array([ 1, 31,  4,  5, 90, 64, 11, 10,  3,  2, 11,  4])

In [98]:
np.vstack([a,b,c])

array([[ 1, 31,  4,  5, 90, 64],
       [11, 10,  3,  2, 11,  4],
       [13, 12,  3,  2, 11,  4]])

In [99]:
np.hstack([a,b])

array([ 1, 31,  4,  5, 90, 64, 11, 10,  3,  2, 11,  4])

In [217]:
np.random.rand(20)

array([0.34529746, 0.79658868, 0.44614623, 0.78274941, 0.99047178,
       0.30024834, 0.14300583, 0.90130844, 0.54155938, 0.97474037,
       0.6366044 , 0.99391302, 0.5460708 , 0.52642593, 0.1354279 ,
       0.35570517, 0.02621857, 0.16039518, 0.74563719, 0.03039969])

In [122]:
np.random.randint(1,10,5)

array([7, 5, 3, 3, 7], dtype=int32)

In [197]:
np.random.seed(1)
np.random.randint(100,200,8)

array([137, 112, 172, 109, 175, 105, 179, 164], dtype=int32)

In [207]:
np.random.random_sample(20)

array([0.74382585, 0.19542948, 0.58135893, 0.97001999, 0.8468288 ,
       0.23984776, 0.49376971, 0.61995572, 0.8289809 , 0.15679139,
       0.0185762 , 0.07002214, 0.48634511, 0.60632946, 0.56885144,
       0.31736241, 0.98861615, 0.57974522, 0.38014117, 0.55094822])