In [13]:
# pip install tensorflow matplotlib   (if needed)
import numpy as np
import matplotlib.pyplot as plt
import keras
from keras import layers
 
# float64 so the tiny late-iteration numbers match the slides
# (the default float32 is too coarse to show values like 1e-9)
 
x = np.array([1, 2, 4, 5, 6], dtype="float64").reshape(-1, 1)   # size (Ropani)
y = np.array([11, 20, 38, 47, 56], dtype="float64").reshape(-1, 1)  # price (Crores)
 
print(np.hstack([x, y]))

[[ 1. 11.]
 [ 2. 20.]
 [ 4. 38.]
 [ 5. 47.]
 [ 6. 56.]]


In [14]:
x

array([[1.],
       [2.],
       [4.],
       [5.],
       [6.]])

In [15]:
y

array([[11.],
       [20.],
       [38.],
       [47.],
       [56.]])

In [16]:
model = keras.Sequential([
    keras.Input(shape=(1,)),
    layers.Dense(
        1,  #neurons = 1
        kernel_initializer="zeros",  #w=0
        bias_initializer="zeros"  #b=0
    ),
])

In [17]:
model

<Sequential name=sequential_1, built=True>

In [18]:
model.compile(
    optimizer=keras.optimizers.SGD(learning_rate=0.03),  # plain gradient descent, alpha = 0.03
    loss="mse"   #(1/n) * sum((y_hat-y)^2)
)

model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_1 (Dense)                      │ (None, 1)                   │               2 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 2 (8.00 B)

 Trainable params: 2 (8.00 B)

 Non-trainable params: 0 (0.00 B)

In [19]:
history = model.fit(
    x, y,
    epochs=5,
    batch_size=5,   #all 5 rows in one batch -> true gradient descent
    shuffle=False,
    verbose=1,
)

Epoch 1/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 547ms/step - loss: 1462.0000
Epoch 2/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 1.4971
Epoch 3/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - loss: 0.0015
Epoch 4/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 1.5674e-06
Epoch 5/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 1.4792e-09


In [21]:
w, b = model.get_weights()
print(f"Learned: w={w[0,0]:.6f}, b={b[0]:.6f}")

Learned: w=9.000000, b=2.000000
